---
Device:
  Version: 1.0
  ID: 1

Pig:
  Avg_Weight: 42
  Lift_pig: False

# Relays Configs
Relay:
  Lift_pin: 22
  Lower_pin: 5

# Scale Configs
Scale:
  Ratio: false
  Offset: false
  ODR_SET: 10
  Default_readouts: 10

# Timing
Timing:
  Before_lift: 5
  Lift_time: 2
  Stationary_pause: 5
  Lower_time: 2.5
  
# Power Monitoring Configs
Power:
  FLOAT_DP: 3
  IN0: -1 # 1 if anything is connected
...