---
Device:
  Version: 1.0
  ID: 1

FS:
   Data_dir: './log'

Pig:
  Min_Weight: 10
  Lift_pig: False

# Relays Configs
Relay:
  Lift_pin: 5
  Lower_pin: 22

# Scale Configs
Scale:
  Ratio: false
  Offset: false
  ODR_SET: 10
  Default_readouts: 10

# Timing
Timing:
  Before_lift: 5
  Lift_time: 3
  Stationary_pause: 5
  Lower_time: 6
  
# Power Monitoring Configs
Power:
  FLOAT_DP: 3
  IN0: -1 # 1 if anything is connected
...