---
Device:
  Version: 1.0
  ID: 1

Pig:
  Avg_Weight: 42
  Lift_pig: False

# Relays Configs
Relay:
  LIFT_PIN: 22
  LOWER_PIN: 5
  DELAY: 20


# Scale Configs
Scale:
  RATIO: false
  OFFSET: false
  ODR_SET: 10
  Default_readouts: 10

# Power Monitoring Configs
Power:
  FLOAT_DP: 3
  IN0: -1 # 1 if anything is connected
...