---
Device:
  Version: 1.0
  ID: 1

Pig:
  Avg_Weight: 42
  Lift_pig: False

# Relays Configs
Relay:
  Lift_pin: 22
  Lower_pin: 5
  Timing:
    Lift_time: 0
    Lower_time: 0
    Pause: 0
    Sway_delay: 0


# Scale Configs
Scale:
  Ratio: false
  Offset: false
  ODR_SET: 10
  Default_readouts: 10

# Power Monitoring Configs
Power:
  FLOAT_DP: 3
  IN0: -1 # 1 if anything is connected
...